### ISSUE TITLE
no output at -search

### ISSUE THREAD

**Issue by TukangM** [adityakumar48/Whatsapp-Bot-AI#6]
**Describe the bug**

**To Reproduce**
1. setup .env like normal
2. connect whatsapp then
3. -help -aboung -meme works
4. -search no output

**Expected behavior**
when -search the bot was no output

**Screenshots**
![image](https://github.com/adityakumar48/Whatsapp-Bot-AI/assets/91467886/0d86a0e3-e4f2-466e-952e-249b7fb58e37)

**Desktop (please complete the following information):**
 - OS: Windows 10, host server at ubuntu
 - Browser: edge

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 10 2022
 - OS: Nusantara OS
 - Browser edge, chrome

**Comment by adityakumar48** [comment]
In case you chatting personally you don't need to use '-search' it is used only in group chats, instead you directly message the bot it will respond according to your chat or question
